### PR TITLE
Automatically accept SDK licenses

### PR DESCRIPTION
**Pull request by lfuelling**
This pull request introduces the use of expect to automatically accept the SDK license.

### CODE REVIEW

**Comment by aerialls** [comment]
Hello @lfuelling 

Thanks for the update 👍

**Comment by lfuelling** [comment]
No problem 😄 

I still have issues with this. Building the container works as it should but expect fails to accept the license when building using the container in GitLab.

**Comment by aerialls** [comment]
I've fixed my mistake.

I'm using something pretty similar to the README file in production and it's working like a charm for us. Did you change anything?

**Comment by lfuelling** [comment]
I think I'm using exactly the same:
```yaml
image: livexp/android-sdk:latest
before_script:
  - java -version
  - docker-android-sdk-install extra-android-m2repository,tools,extra-android-support,build-tools-25.0.2,android-23,android-24,android-25
stages:
  - build
build_with_tests:
  stage: build
  script:
    - ./gradlew build
  only:
    - master
```

Here's the shortened buildlog:

```
-------------------------------
License id: android-sdk-license-c81a61d9
Used by: 
 - Android SDK Build-tools, revision 23.0.2
  - Android Support Repository, revision 44
-------------------------------

Terms and Conditions
```
**[Lots of license text]**
```
Notwithstanding this, you agree that Google shall still be allowed to apply for injunctive remedies (or an equivalent type of urgent legal relief) in any jurisdiction.


November 20, 2015
Do you accept the license 'android-sdk-license-c81a61d9' [y/n]: 
Installing Archives:
  Preparing to install archives
  Downloading Android SDK Tools, revision 25.2.5
     (8%, 12034 KiB/s, 20 seconds left)
     (14%, 13276 KiB/s, 17 seconds left)
```
**[Lots of downloads, afterwards `./gradlew build` is called and downloads even more]**
```
Checking the license for package Android SDK Platform 25 in /usr/local/bin/android-sdk/licenses
Warning: License for package Android SDK Platform 25 not accepted.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':mobile'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 25].
```

**Pull request merged**
